# Generated by Django 6.0.3 on 2026-04-07 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(default='A', max_length=10)),
                ('academic_year', models.CharField(max_length=20)),
                ('current_year', models.IntegerField(default=1)),
                ('current_semester', models.IntegerField(blank=True, null=True)),
                ('semester_start_date', models.DateField(blank=True, null=True)),
                ('semester_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college_name', models.CharField(max_length=200)),
                ('college_code', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField()),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['admin_email'], name='psapp_colle_admin_e_151dfb_idx'), models.Index(fields=['college_code'], name='psapp_colle_college_7ae2b9_idx'), models.Index(fields=['is_verified'], name='psapp_colle_is_veri_bdcfd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='psapp.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective'), ('Lab', 'Lab')], default='Core', max_length=20)),
                ('batch_name', models.CharField(default='Main', help_text="e.g., 'Group A', 'Batch 1', or 'Main'", max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=50)),
                ('semester', models.IntegerField(blank=True, default=1, null=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('parent_course_id', models.IntegerField(blank=True, null=True)),
                ('total_hours', models.IntegerField(default=45)),
                ('is_assigned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to='psapp.academicclass')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('start_session', models.IntegerField(default=1)),
                ('end_session', models.IntegerField(default=1)),
                ('session_duration', models.IntegerField(default=1)),
                ('current_semester', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='psapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established_year', models.IntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='psapp.college')),
            ],
        ),
        migrations.AddField(
            model_name='academicclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='psapp.department'),
        ),
        migrations.CreateModel(
            name='DepartmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=50)),
                ('semester', models.IntegerField(blank=True, default=0, null=True)),
                ('course_type', models.CharField(choices=[('Core', 'Core Subject'), ('Elective', 'Elective Subject'), ('Lab', 'Practical/Lab')], default='Core', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='psapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='NewFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college_name', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('college_email', models.EmailField(max_length=254, unique=True)),
                ('mobile_num', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('faculty_reg_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('department_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='psapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='psapp.newfaculty')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='psapp.newfaculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psapp.newfaculty'),
        ),
        migrations.CreateModel(
            name='ClassAssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField(default=45)),
                ('batch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_list_json', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.academicclass')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.college')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.departmentcourse')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.newfaculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_type', models.CharField(choices=[('Official', 'Official'), ('Personal', 'Personal')], default='Official', max_length=20)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='psapp.academicclass')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_students', to='psapp.college')),
                ('created_by_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psapp.newfaculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='psapp.student'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('OD', 'On Duty')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='psapp.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_start', models.DateField()),
                ('semester_end', models.DateField()),
                ('working_days', models.TextField(default='["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]')),
                ('periods_per_day', models.IntegerField(default=7)),
                ('break_after_period', models.IntegerField(default=0)),
                ('academic_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_settings', to='psapp.academicclass')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('period_number', models.IntegerField()),
                ('is_break', models.BooleanField(default=False)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psapp.academicclass')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psapp.course')),
            ],
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['course', 'date'], name='psapp_atten_course__340a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date'], name='psapp_atten_date_8476e7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['course'], name='psapp_atten_course__fa81fd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['created_at'], name='psapp_atten_created_886238_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('course', 'date', 'start_session', 'end_session')},
        ),
        migrations.AddIndex(
            model_name='academicclass',
            index=models.Index(fields=['department'], name='psapp_acade_departm_78ccf7_idx'),
        ),
        migrations.AddIndex(
            model_name='academicclass',
            index=models.Index(fields=['class_name'], name='psapp_acade_class_n_7b7c47_idx'),
        ),
        migrations.AddIndex(
            model_name='academicclass',
            index=models.Index(fields=['current_year'], name='psapp_acade_current_a73797_idx'),
        ),
        migrations.AddIndex(
            model_name='academicclass',
            index=models.Index(fields=['is_active'], name='psapp_acade_is_acti_6a3dfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicclass',
            unique_together={('department', 'class_name', 'section', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='newfaculty',
            index=models.Index(fields=['college_email'], name='psapp_newfa_college_9e27af_idx'),
        ),
        migrations.AddIndex(
            model_name='newfaculty',
            index=models.Index(fields=['faculty_reg_id'], name='psapp_newfa_faculty_eaa572_idx'),
        ),
        migrations.AddIndex(
            model_name='newfaculty',
            index=models.Index(fields=['is_verified'], name='psapp_newfa_is_veri_921fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='newfaculty',
            index=models.Index(fields=['department_link'], name='psapp_newfa_departm_72af3b_idx'),
        ),
        migrations.AddIndex(
            model_name='newfaculty',
            index=models.Index(fields=['college_name'], name='psapp_newfa_college_7e29f0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['reg_no'], name='psapp_stude_reg_no_1652ff_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_type'], name='psapp_stude_student_8c74d2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_by_faculty'], name='psapp_stude_created_2a0ffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('college', 'reg_no')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'student'], name='psapp_atten_session_95c87a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'status'], name='psapp_atten_student_d5fc2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('academic_class', 'day', 'period_number')},
        ),
    ]
